#!/bin/bash

cd /etc

## Test if the local host if Arch-based

if [ -d /etc/pacman.d ]
then
	## Run the Arch version of the update command
	sudo pacman -Syu
fi

## Test if the local host is Debian-based
if [ -d /etc/apt ]
then
	## Run the Debian version of update command
	sudo apt update && sudo apt upgrade -y
fi
